# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QApplication
from utils import LayersNum, GoodsQuantity, GoodsColor
import cv2 as cv
from PIL import Image


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        Form.setFont(font)
        # self.ImageOrigin = QtWidgets.QListView(Form)
        # self.ImageOrigin.setGeometry(QtCore.QRect(50, 70, 350, 300))
        # self.ImageOrigin.setObjectName("ImageOrigin")
        self.ImageOriginLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageOriginLabel.setGeometry(QtCore.QRect(50, 70, 350, 300))
        self.ImageOriginLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageOriginLabel.setObjectName("ImageOriginLabel")
        # 图片填充整个框
        self.ImageOriginLabel.setScaledContents(True)
        # self.ImageTrans = QtWidgets.QListView(Form)
        # self.ImageTrans.setGeometry(QtCore.QRect(500, 70, 350, 300))
        # self.ImageTrans.setObjectName("ImageTrans")
        self.ImageTransLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageTransLabel.setGeometry(QtCore.QRect(500, 70, 350, 300))
        self.ImageTransLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageTransLabel.setObjectName("ImageOriginLabel")
        # 图片填充整个框
        self.ImageTransLabel.setScaledContents(True)
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 600, 100, 50))
        self.pushButton_1.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 600, 100, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 600, 100, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(310, 460, 300, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 460, 140, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(350, 10, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 460, 100, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_4.clicked.connect(self.openImage)
        self.pushButton_1.clicked.connect(self.ShowLayersNum)
        self.pushButton_2.clicked.connect(self.ShowGoodsQuantity)
        self.pushButton_3.clicked.connect(self.ShowGoodsColor)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_1.setText(_translate("Form", "货架层数"))
        self.pushButton_2.setText(_translate("Form", "商品个数"))
        self.pushButton_3.setText(_translate("Form", "商品颜色"))
        self.label.setText(_translate("Form", "请选择商品图片："))
        self.pushButton_4.setText(_translate("Form", "图片路径"))

    # 选择本地图片上传
    def openImage(self):
        # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        global imgName
        # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名
        # 第二个返回值imgType记录文件的类型
        imgName, imgType = QFileDialog.getOpenFileName(
            self.centralwidget, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
        # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        print(QtGui.QPixmap(imgName))
        jpg = QtGui.QPixmap(imgName).scaled(self.ImageOriginLabel.width(),
                                            self.ImageOriginLabel.height())
        # 在label控件上显示选择的图片
        self.ImageOriginLabel.setPixmap(jpg)
        # print(imgName)
        # 显示所选图片的本地路径
        self.lineEdit.setText(imgName)

    # 显示变化之后的图像
    def openImage2(self, image):
        # cv.imshow('res', res)
        res = Image.fromarray(image)
        res = res.toqpixmap()
        print(res)
        jpg = res.scaled(self.ImageOriginLabel.width(),
                           self.ImageOriginLabel.height())
        # 在label控件上显示选择的图片
        self.ImageTransLabel.setPixmap(jpg)

    # 显示货架层数
    def ShowLayersNum(self):
        result = LayersNum(imgName)
        self.openImage2(result)

    # 显示货物数量
    def ShowGoodsQuantity(self):
        GoodsColor(imgName)

    # 显示货物颜色
    def ShowGoodsColor(self):
        GoodsColor(imgName)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())